### ISSUE TITLE
Unauthorized user path

### ISSUE THREAD

**Issue by lujacky380** [Citraro/EmployeeTempTracker#35]
When user tries to go to a page without login credentials, they will be sent to login page (unauthorized user)

Use (!lm.sessionValid) check on each page, redirect to login page if not valid.

Also there is currently an issue with the url showing username/password

**Comment by ahedgpath** [comment]
1. Ran into stateless issues (i.e. user object is not retained and referenceable for session checks from various controllers). So implemented auth cookies:
  a. Cookie is created after successful login (i.e. after API call returns session id)
  b. Cookie is deleted when user clicks 'Logout' on dashboard
  c. Cookies are set to expire on sliding schedule of 15 mins (i.e. if no get/post calls are made)
2. Users who are not authorized (i.e. do not have an active cookie) are redirected to login page if they try to access other pages
3. (Resolved) URL no longer displays login parameters

NOTES: 
- Could not get the async classes to work on the logic controllers. So they're in the main controllers for now.
- SessionID is being stored in the cookie, so if we wanted to make API calls for each GET/POST, we could probably create a comparison method in the API controller to make sure the session id is still active. I don't think it's a huge issue to just rely on the cookie expiration since it expires after 15 mins of inactivity anyway.
